export {
  DEFAULT_AUDIO_SETTINGS,
  DEFAULT_INITIAL_STATE_OPTIONS,
  DEFAULT_TURN_TIME_SECONDS,
  MAX_TURN_TIME_SECONDS,
  MIN_TURN_TIME_SECONDS,
  STANDARD_CUSTOMER_RULES,
  clampTurnTime
} from "../game/sessionConfig";

export const CUSTOMER_PERSONALITIES_ENABLED = import.meta.env.VITE_ENABLE_CUSTOMER_PERSONALITIES === "true";
export const CAMPAIGN_RULE_OPTIONS = { customerPersonalitiesEnabled: CUSTOMER_PERSONALITIES_ENABLED } as const;
